### ISSUE TITLE
Easily Exceed Environment Limits With Gutter E2BIG

### ISSUE THREAD

**Issue by RaniSputnik** [Gamefroot/Gamefroot-Texture-Packer#4]
Using gutter leads to including images in the generateImage command 10 times. If you are packing an animation then you often times have 30+ frames leading to 300 absolute image paths included in a single command! This will need to be fixed by breaking down commands into smaller chunks, multiple passes to generate the image.

**Comment by BenjaminHarding** [comment]
Yus! I will  be able to compile my game soon! 

Nice work Mr @RaniSputnik
