### ISSUE TITLE
exec identify command in generator.js leads to empty sprites with new versions of Imagemagick

### ISSUE THREAD

**Issue by pvanhemmen** [Gamefroot/Gamefroot-Texture-Packer#7]
In line 102 of generator.js the filePath is split by the opening bracket character `[`. In my installation of Imagemagick the identify command does not output indexes anymore, which leads to empty file paths.

One solution would be to check for the existense of the opening bracket before splitting the string:

```
var filePath = size;
if (size.indexOf('[') !== -1) {
    filePath = size.substring(0, size.indexOf('['));
}
```

Hope that helps!

**Comment by Ryanc1256-zz** [comment]
@pvanhemmen yes, just noticed it on my installation too....

**Comment by Ryanc1256-zz** [comment]
thanks for the info, ill push a new version to npm
